@startuml associations_only
set namespaceSeparator none
' Héritage
Fish --|> Animal : hérite
Shark --|> Animal : hérite

' Associations
Planet "1" *--> "*" Fish : contient
Planet "1" *--> "*" Shark : contient
SimulationControl --> Planet : crée
Interface -->  SimulationControl: pilote
SimulationControl --> DataHandler : utilise
DataHandler --> PersistenceHandler : utilise pour persistance
@enduml